version: 2.1
workflows:
  version: 2.1
  build_all:
    jobs:
      - build_and_test
  build_master:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk libharfbuzz-dev libfribidi-dev libxcb1-dev
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python app/tests.py
  deploy:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Variables environment
          command: |
            echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=fakeimg' >> $BASH_ENV 
      - run:
          name: Build and push Docker image
          command: |
            docker build --no-cache -t rydgel/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push rydgel/$IMAGE_NAME:$TAG
            docker tag rydgel/$IMAGE_NAME:$TAG rydgel/$IMAGE_NAME:latest
            docker push rydgel/$IMAGE_NAME:latest
